# Terraform Backend Configuration for dev environment
# Generated by bootstrap script on Mon Jul  8 18:22:42 UTC 2025

terraform {
  backend "azurerm" {
    resource_group_name  = "rg-terraform-state-dev-cus-001"
    storage_account_name = "staksdevcus001tfstate"
    container_name       = "terraform-state"
    key                  = "dev/terraform.tfstate"
    use_oidc             = true
  }
}
