# Terraform Variables for dev environment
# Generated by bootstrap script on Mon Jul  8 18:22:42 UTC 2025

environment = "dev"
location = "Central US"
managed_identity_client_id = "b4f707fd-a97a-4e80-abd9-c8984190fd11"
