#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git
  - unzip
  - jq
  - ca-certificates
  - gnupg
  - lsb-release

# Install Azure CLI
runcmd:
  # Install Azure CLI
  - curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  
  # Install kubectl
  - az aks install-cli
  
  # Install Helm
  - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
  - chmod 700 get_helm.sh
  - ./get_helm.sh
  - rm get_helm.sh
  
  # Install Docker (for development if needed)
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - usermod -aG docker ${admin_username}
  - rm get-docker.sh
  
  # Create tools directory
  - mkdir -p /home/${admin_username}/tools
  - chown ${admin_username}:${admin_username} /home/${admin_username}/tools
  
  # Set up kubectl completion
  - echo 'source <(kubectl completion bash)' >> /home/${admin_username}/.bashrc
  - echo 'alias k=kubectl' >> /home/${admin_username}/.bashrc
  - echo 'complete -F __start_kubectl k' >> /home/${admin_username}/.bashrc

write_files:
  - path: /home/${admin_username}/README.md
    owner: ${admin_username}:${admin_username}
    permissions: '0644'
    content: |
      # Jump VM for AKS Private Cluster Access
      
      This VM provides secure access to the private AKS cluster via Azure Bastion.
      
      ## Pre-installed Tools:
      - Azure CLI (az)
      - kubectl
      - Helm 3
      - Docker
      - curl, wget, git, jq
      
      ## Quick Start:
      1. Login to Azure: `az login`
      2. Get AKS credentials: `az aks get-credentials --resource-group rg-aks-dev-cus-001 --name aks-cluster-dev-cus-001`
      3. Verify cluster access: `kubectl get nodes`
      
      ## Deploy Add-ons:
      Run the deployment script to install nginx-ingress and cert-manager:
      ```bash
      curl -O https://raw.githubusercontent.com/[your-repo]/scripts/deploy-addons.sh
      chmod +x deploy-addons.sh
      ./deploy-addons.sh
      ```
      
      ## Useful Aliases:
      - `k` = `kubectl`
      
      Happy Kubernetes administration!

final_message: |
  Jump VM setup complete!
  Azure CLI, kubectl, Helm, and Docker are installed.
  Use 'az login' to authenticate and then 'az aks get-credentials' to access the cluster.
