name: 🏗️ Infrastructure Orchestration

on:
  workflow_dispatch:
    inputs:
      setup_environments:
        description: 'Setup GitHub environments first'
        required: false
        default: false
        type: boolean
      target_environment:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      action:
        description: 'Terraform action to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  setup-environments:
    name: 🌍 Setup GitHub Environments
    if: ${{ inputs.setup_environments == true }}
    uses: ./.github/workflows/setup-environments.yml
    secrets: inherit

  setup-backend:
    name: 🔧 Setup Terraform Backend
    needs: [setup-environments]
    if: ${{ always() && !failure() }}
    uses: ./.github/workflows/terraform-backend-setup.yml
    with:
      environment: ${{ inputs.target_environment }}
      force_recreate: false
    secrets: inherit

  deploy-infrastructure:
    name: 🚀 Deploy Infrastructure
    needs: [setup-backend]
    if: ${{ always() && !failure() }}
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      environment: ${{ inputs.target_environment }}
      action: ${{ inputs.action }}
      auto_approve: false
    secrets: inherit
